name: Check build and linters

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    # Uncomment these lines after fixing main.js in your project
    #- run: npm run svelte-check
    #- run: npm run lint:prod
    #- run: npm run build
